---
- name: Configure Windows 10 to Delete Inactive User Profiles
  hosts: windows_clients
  tasks:
    - name: Set registry entry to delete user profiles after 7 days of inactivity
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DeleteRoamingCache
        data: 1
        type: dword
        state: present
    - name: Set registry entry to specify the number of days of inactivity
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy Objects\{48981759-12F2-42A6-A048-028B3973495F}Machine\Software\Policies\Microsoft\Windows\System
        name: CleanupProfiles
        data: 7
        type: dword
        state: present
